#!/bin/sh

set -e

dpkg-divert --package systemd-shim --add --rename --divert \
	/usr/share/dbus-1/system-services/org.freedesktop.systemd1.service.systemd \
	/usr/share/dbus-1/system-services/org.freedesktop.systemd1.service

# Automatically added by dh_installdeb
dpkg-maintscript-helper mv_conffile /etc/dbus-1/system.d/org.freedesktop.systemd1.conf /etc/dbus-1/system.d/org.freedesktop.systemd-shim.conf 6-2 systemd-shim -- "$@"
# End automatically added section

