# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 946698359);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 946698479);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 946697998);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 946698239);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 946698119);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 1);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 22);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.slowStartup.averageTime", 21959);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20141013200736");
user_pref("browser.startup.homepage_override.mstone", "33.0");
user_pref("datareporting.sessions.current.activeTicks", 16);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.totalTime", 946698566);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "ubufox%40ubuntu.com:2.9,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:33.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.installCache", "[{\"name\":\"app-system-share\",\"addons\":{\"ubufox@ubuntu.com\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"mtime\":1400850602000,\"rdfTime\":1400850602000}}},{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1413239775000,\"rdfTime\":1413239775000}}}]");
user_pref("extensions.lastAppVersion", "33.0");
user_pref("extensions.lastPlatformVersion", "33.0");
user_pref("extensions.pendingOperations", false);
user_pref("gecko.buildID", "20141013200736");
user_pref("gecko.mstone", "33.0");
user_pref("idle.lastDailyNotification", 946698159);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("places.database.lastMaintenance", 946698165);
user_pref("places.history.expiration.transient_current_max_pages", 52578);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 946698165);
user_pref("toolkit.startup.last_success", 946697877);
user_pref("toolkit.telemetry.previousBuildID", "20141013200736");
